version: '3'
services:
  
  java:
    build: ./docker/java
    container_name: java
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./server/src:/usr/src:cached
    depends_on:
      - db

  db:
    image: postgres:13.1
    container_name: db
    environment:
      
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
      - ./docker/postgresql/initdb:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:4.7.8
    container_name: adminer
    ports:
      - "9000:8080"
    depends_on:
      - db

volumes:
  database:


